ansible_become_pass: ENC[AES256_GCM,data:Nys2GI5CN7nhvJiM,iv:9oQ0bpxW3bDCDHnTWnLD5yrgi+F0eKRO9Hf63xxHrDI=,tag:CIId0GJ8IfiNvMtH4IeU9g==,type:str]
devops_prod_ip: ENC[AES256_GCM,data:zMHzoNMW7Hdtg+mMrA==,iv:Yc4aNJtKPFnmQ6vsGVLiauB0hTM2fr06DvpF/WD/Zps=,tag:UZi4UyTznFh9iaDToXCENQ==,type:str]
devops_test_ip: ENC[AES256_GCM,data:ZZCYalS+7hzcyxSfIQ==,iv:zfIDkmIfQLeHkeagkie/MJhMUnxIj4g2gUJtD1Bs40Q=,tag:qWCXdQ+jS7YoMZf3SUsjvg==,type:str]
homelab_subnet: ENC[AES256_GCM,data:9f6+mFvzEon11/XrpZc=,iv:EbxCol55d1E0lwj2X1e0yEL0hp2KY5dHzj7opJnggMM=,tag:9YyByHOczA5bwRF0bZecDw==,type:str]
hypervisor_host: ENC[AES256_GCM,data:7w9ne7gEKcPdBHQOtA4N/Y/Ti89UXXWqsOekfxbMW1zYSGcfBv7T8KuWuN8w,iv:hrrbrFE2od8TXDxLccV/F0b9Aj+5+WBL6PFQ8tvaUDk=,tag:vTF2rVr61k6ivds2cO+/7w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5eFpwbWREK21pbXlaRHg2
            Nlc2SVRXRXY1NHJpTlRDbkFNOERFOWMzWmdRCjJEcDVlenFDaDBldWkzV3FRSXdF
            eFNPU2lRay9UeGwyZi9sVGxtam5obkEKLS0tIFFRV3hBRFdyeEpuUHlqNUZSaGU2
            SStzbXNwYmkyd1VWYWlZNmYvOUNYYkEKyQz8gd1GFHvAqmusbQ/36X5FjboMxD+6
            +c+He8+VYRZj0i8fuIk8QTW7hGC3HoRijWkeMioroIexEHNTpjELmA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1smedwh0yuxgyv5w4n6pj27cmxuh7ulu6aacu7gasphx3u7sjs46smuexua
    lastmodified: "2026-08-09T12:43:22Z"
    mac: ENC[AES256_GCM,data:tBNNomcFjc0WP/hiin3zQ65fKi8PKGy77G6jzvv2GI6J/zPH8hnT9NZ15QMZ4a8ATFvYY8zvsJhsFCGxsikn98SlvQ96tidO09BGHVXDDMhHRRb5jKCEyl4bpj7P4+/QGJiuoKhn5MmA4izkSpsFh5c5uO0GmfRXFoWkSAjKZlo=,iv:cM7ZCRfguCd8+p9Tb8dDZx7y/LFp36mRXMa/URyNjoM=,tag:SBvGMxFtU22qEjDd8o+QNA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
