devops_prod_ip: ENC[AES256_GCM,data:zMHzoNMW7Hdtg+mMrA==,iv:Yc4aNJtKPFnmQ6vsGVLiauB0hTM2fr06DvpF/WD/Zps=,tag:UZi4UyTznFh9iaDToXCENQ==,type:str]
devops_test_ip: ENC[AES256_GCM,data:ZZCYalS+7hzcyxSfIQ==,iv:zfIDkmIfQLeHkeagkie/MJhMUnxIj4g2gUJtD1Bs40Q=,tag:qWCXdQ+jS7YoMZf3SUsjvg==,type:str]
homelab_subnet: ENC[AES256_GCM,data:9f6+mFvzEon11/XrpZc=,iv:EbxCol55d1E0lwj2X1e0yEL0hp2KY5dHzj7opJnggMM=,tag:9YyByHOczA5bwRF0bZecDw==,type:str]
hypervisor_host: ENC[AES256_GCM,data:7w9ne7gEKcPdBHQOtA4N/Y/Ti89UXXWqsOekfxbMW1zYSGcfBv7T8KuWuN8w,iv:hrrbrFE2od8TXDxLccV/F0b9Aj+5+WBL6PFQ8tvaUDk=,tag:vTF2rVr61k6ivds2cO+/7w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5eFpwbWREK21pbXlaRHg2
            Nlc2SVRXRXY1NHJpTlRDbkFNOERFOWMzWmdRCjJEcDVlenFDaDBldWkzV3FRSXdF
            eFNPU2lRay9UeGwyZi9sVGxtam5obkEKLS0tIFFRV3hBRFdyeEpuUHlqNUZSaGU2
            SStzbXNwYmkyd1VWYWlZNmYvOUNYYkEKyQz8gd1GFHvAqmusbQ/36X5FjboMxD+6
            +c+He8+VYRZj0i8fuIk8QTW7hGC3HoRijWkeMioroIexEHNTpjELmA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1smedwh0yuxgyv5w4n6pj27cmxuh7ulu6aacu7gasphx3u7sjs46smuexua
    lastmodified: "2026-09-29T11:09:42Z"
    mac: ENC[AES256_GCM,data:+uZRvzpwO2o9t1RiDow3Peh6eAIaM7HjSlSPjpLSWMcWqwuFaHJvPUEId/tI70cjIRuAEFbJ7TzmXWY1zDsp12eQYLcpvC3QcKztwzUmbkWHl8iW8iuAA6Rs22YZEWR9a2qfKh5/+2kxoLjU2IlXYgrNTqhOtRCHvPrEqGA78yc=,iv:VotzJSM+6gM4emPtQmaVykK1Bs8qy2TSMzA9wT5qxuU=,tag:Brtugf1XRxK2l7bqwAA7vg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
